
# libraries
import argparse
from multiprocessing import Pool, cpu_count
import os
#import time
import zipfile
# self-implementations
from backup_tool.restore import restore_from_manifest

from backup_tool.mysql_source import MySQLSource
from backup_tool.config import load_mysql_config, load_aws_config

from backup_tool.output_sql import SchemaExport
from backup_tool.output_csv import CsvExport

from backup_tool.s3_upload_func import s3_multipart_upload
from backup_tool.s3_source import S3Source
from backup_tool.local_to_s3_zip import local_to_s3_zip

# command example below
# python main_arg.py backup -schema-no-data -s3 -output-dir test11
"""
・ローカル保存可
 python main_arg.py backup -zip -output-dir test11
"""
def main():
# definitions
    requirements = [ # name, default, description
        ["mode", "backup",  "select mode from backup / generate / restore"],
    ]
    flags = [ # name, description
        ["-debug", "show debug massages"],
        ["-schema-no-data", "output schema with only structure info"],
        ["-zip", "output in zipping"],
        ["-s3", "output into s3 with zipping"],
        ["-local-s3", "output into both local and s3 with zipping "],
    ]
    options = [ # name, default value, number of arg, description
        #["-db-password", "", None, "password of your database"],
        ["-db-tables", "", "+", "one or several specific table name you wanna backup\nbackup all if not selected"],
        ["-output-types", ["csv"], "+", "one or several plain file types you want \nby default: csv \ncan be: csv"],
        ["-output-dir", "./backup", None, "directory you wanna backup into \nby default: backup"],
        ["-settings-path", ".mysql-backup/settings.env", None, "by default: .mysql-backup/settings.env"],
        ["-restore-from", "backup/", None, "the directory or zip file you wanna restore data from"],
    ]


# initializes
    parser = argparse.ArgumentParser(
        description="""
mysql-backup tool
usage:
    -generate: generates settings.env with format
    -backup: backup all or specific data / schema into specific format
    -restore: restore data / schema from backuped files
              only -restore-from option required
this requires .env file
...set some parameters such as sql password, host or database name via settings.env generated by -generate
""",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    flags_group = parser.add_argument_group("flags")


    for requirement in requirements:
        parser.add_argument(
            requirement[0],
            default=requirement[1],
            help= requirement[2],
            nargs='?',
        )
    for flag in flags:
        flags_group.add_argument(
            flag[0],
            action= "store_true",
            help= flag[1],
        )
    for option in options:
        parser.add_argument(
            option[0],
            default= option[1],
            nargs= option[2],
            help= option[3],
        )

    args = parser.parse_args()


# processes
    match args.mode:
        case "backup": pass
        case "generate":
            os.makedirs(".mysql-backup/", exist_ok=True)
            with open(
                f".mysql-backup/settings.env",
                "w", encoding="utf-8"
            ) as f:
                f.write("""
MYSQL_HOST=
MYSQL_PORT=
MYSQL_USER=
MYSQL_PASSWORD=
MYSQL_DATABASE=

AWS_PROFILE=
S3_REGION=
S3_BUCKET=
""")
            with open(
                ".gitignore",
                "a", encoding="utf-8"
            ) as gi:
                gi.writelines(".mysql-backup")

            return None
        case "restore":
            try:
                path = args.restore_from
                is_debug = args.debug
                config = load_mysql_config(
                    setting_file_path=args.settings_path,
                    is_debug=is_debug
                )
                restore_from_manifest(
                    rstr_from=path,
                    mysql_config=config,
                )

                return None
            except Exception as e:
                print("main arg")
                print(e)
        case _:
            parser.print_help()
            return None

    #backup
    is_debug = args.debug
    config = load_mysql_config(
        setting_file_path=args.settings_path,
        is_debug=is_debug
    )
    # judge whether each tables exist
    for_check_tables = MySQLSource(config=config)
    for_check_tables.connect()
    tables_exists = for_check_tables.list_tables()
    tables_ok = []

    if not args.db_tables:
        tables_ok = tables_exists
    else: 
        for t in args.db_tables:
            if t in tables_exists:
                tables_ok.append(t)
            else:
                print(f"the table {t} doesn't exist")
                print("you wanna continue without it?")
                ans = ""
                while not (ans == "y" or ans == "n"):
                    ans = input("y/n: ")
                match ans:
                    case "y":
                        print("yes")
                        continue
                    case "n":
                        print("no")
                        return None
                    case _: print("aaaaaaaaaaaaaaaaaaaaaa")
    for_check_tables.close()

    work: list[MySQLSource] = []
    # contain any backup process, called in multiprocessing
    # must be given instances of class which extends from MySQLSource
    # but the class must recieve 1 table name
    # 1 instance for 1 table thus multiprocessing for each tables
    #ps, s3 process cant be integrated into this


    directory = args.output_dir

    # to s3
    if args.s3:
        s3_config = load_aws_config(
            setting_file_path=args.settings_path,
        )
        s3_source = S3Source(
            mysql_config=config,
            s3_config=s3_config,
            target_file=f"{directory}.zip"
        )

        # whether do plains
        plain = args.output_types
        for p in plain:
            match p:
                case "csv":
                    pass
                case _:
                    print("error: invalid value on output types")
        # multi part upload
        if args.schema_no_data:
            s3_multipart_upload(
                source=s3_source,
                tables=tables_ok,
                plains=plain,
                sql_no_data=True,
            )
        else:
            s3_multipart_upload(
                source=s3_source,
                tables=tables_ok,
                plains=plain,
            )
    # s3 process ends here
    
    # to local
    else:
        # whether do schema
        if args.schema_no_data:
            for t in tables_ok:
                schema_work = SchemaExport(
                    config=config,
                    table=t,
                    directory=directory,
                    no_data=True,
                )
                work.append(schema_work)
        else:
            for t in tables_ok:
                schema_work = SchemaExport(
                    config=config,
                    table=t,
                    directory=directory,
                )
                work.append(schema_work)

        # whether do plains
        plain = args.output_types
        if type(plain) == type(""):
            print(plain)
        elif type(plain) == type([]):
            for p in plain:
                match p:
                    case "csv" | ".csv":
                        for t in tables_ok:
                            csv_work = CsvExport(
                                config=config,
                                table=t,
                                directory=directory,
                            )
                            work.append(csv_work)
                    #case "txt" | ".txt":
                        # todo implement txt process here
                    #    pass
                    case _:
                        print("error: invalid value on output types")
        else:
            print("error: invalid value on output types")

        # any work's element executed here
        n = cpu_count()
        with Pool(processes=n) as p:
            p.map(func, work)
        #for w in work:
        #    res = func(w=w)
    # local process ends here

    # zip
    print("args.s3 =", args.s3)
    print("args.zip =", args.zip)
    print("directory =", directory)

    if (not args.s3) and args.zip:
        zip_path = f"{directory}.zip"

        with zipfile.ZipFile(
            zip_path,
            "w",
            compression=zipfile.ZIP_DEFLATED
        ) as zf:
            print("zip読み込み")

            for root, dirs, files in os.walk(directory):
                for file in files:
                    full_path = os.path.join(root, file)

                    zf.write(
                        full_path,
                        arcname=os.path.relpath(
                            full_path,
                            directory
                        )
                    )

        print(f"Created {zip_path}")
        pass
    elif (not args.s3) and args.local_s3:
        # TODO zip function here
        
        s3_config = load_aws_config(
            setting_file_path=args.settings_path,
        )
        local_to_s3_zip(
            s3_config= s3_config,
            output_dir= directory,
        )
    

def func(w: MySQLSource):
    w.connect()
    w.do_output()
    w.close()

if __name__ == "__main__":
    #start = time.perf_counter()
    main()
    #end = time.perf_counter()

    #print(end - start)